config/routes.rb
Rails.application.routes.draw do
  
  resources :references
  resources :skills
  resources :honors
  resources :experiences
  resources :generate

  devise_for :users
  root to: "dashboard#index"
  get 'dashboard/index'


  get 'dashboard/experience'
  
  get 'dashboard/honors'

  get 'dashboard/references'

  get 'dashboard/skills'
  
  get 'dashboard/generate'
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    
    if user_signed_in?
      @User = User.find(current_user.id)
      @experiences = Experience.where("owner = ?", current_user.id)
      @honors = Honor.where("owner = ?", current_user.id)
      @references = Reference.where("owner = ?", current_user.id)
      @skills = Skill.where("owner = ?", current_user.id)
    end
  end

  def experience
    @User = User.find(current_user.id)
    @experiences = Experience.where("owner = ?", current_user.id)
  end

  def courses
    @User = User.find(current_user.id)
    @courses = Course.where("owner = ?", current_user.id)
  end
  
  def honors
     @User = User.find(current_user.id)
    @honors = Honor.where("owner = ?", current_user.id)
  end

  def references
     @User = User.find(current_user.id)
    @references = Reference.where("owner = ?", current_user.id)
  end

  def skills
     @User = User.find(current_user.id)
    @skills = Skill.where("owner = ?", current_user.id)
  end
  
  def generate
    user = User.find(current_user.id)
    @exp = Experience.where("owner = ?", current_user.id)
    @hon = Honor.where("owner = ?", current_user.id)
    @ref = Reference.where("owner = ?", current_user.id)
    @ski = Skill.where("owner = ?", current_user.id)
    Caracal::Document.save '/public/example.docx' do |docx|
      
      docx.style do
        id 'Body'
        name 'body'
        font 'Times New Roman'
        size 24
        
      end
    
      
      docx.p do
        style 'Body'
        text user.first_name, size: 48
        text ' '
        text user.last_name, size: 48
        br
        text "Major: ".concat(user.major)
        br
        text "Department: ".concat(user.department)
        br
        text "Degree Program: ".concat(user.degree_program)
      
      end
      docx.hr
      
      docx.h3 'Work Experience'
      @exp.each do | experience |
        docx.p do
          style 'Body'
          text experience.name, bold: true
          text ", ".concat(experience.start_date), italic: true
          text " - ".concat(experience.end_date), italic: true
          br
          text "  ".concat(experience.description)
          ##br

        end
      end
      
      
      docx.h3 'Skills and Interests'
      @ski.each do | skill |
        docx.p do
          style 'Body'
          text skill.skill_name, bold: true
          br
          text " ".concat(skill.skill_description)
          ##br
        end
      end
      
      
      docx.h3 'Honors and Awards'
      @hon.each do | honor |
        docx.p do
          style 'Body'
          text honor.honor_name, bold: true
          text ", ".concat(honor.honor_date), italic: true
          br
          text " ".concat(honor.honor_description)
          ##br
        end
      end
      
      
      docx.h3 'References'
      @ref.each do | reference |
        docx.p do
          style 'Body'
          text reference.reference_name, bold: true
          br
          text " ".concat(reference.reference_contact_info), italic: true
         ## br
        end
      end
      
      
    end
        
        
        path = File.join(Rails.root, "public")
        send_file(File.join(path, "example.docx"))
        
     
    
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/courses.html.erb
<head>
      <%= javascript_include_tag :defaults %>
         <%= csrf_meta_tag %>
</head>
<p><%= @User.first_name %> <%= @User.last_name %>  </p>


<table class="table table-hover table-bordered">
  <thead>
     
    <tr>
      <th>Course number</th>
      <b>
      <th>Course name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody id="coursesList">
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.course_number %></td>
        <td><%= course.course_name%></td>
        <!-- <td><%= link_to 'Show', course %></td> -->
        <td><%= link_to 'Edit', edit_course_path(course) %>
        <span class= "glyphicon glyphicon-edit" ></span></td>
        <td><%= link_to 'Destroy', course, :method => :delete, data: { confirm: 'Are you sure?' } %>
        <span class= "glyphicon glyphicon-remove" ></span>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add Completed Course', new_course_path, class: "btn btn-default" %>


<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="myModalLabel"> Hello </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="myModalBody">
        World
      </div>
      
    </div>
  </div>
</div>

app/views/dashboard/experience.html.erb
<head>
      <%= javascript_include_tag :defaults %>
         <%= csrf_meta_tag %>
</head>



<table class="table table-hover table-bordered">
  <thead>
    <tr>

      <th>Start date</th>
      <th>End date</th>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody id="experienceList">
    <% @experiences.each do |experience| %>
      <tr data-toggle="modal" data-target="#expModal">

        <td><%= experience.start_date %></td>
        <td><%= experience.end_date %></td>
        <td><%= experience.name %></td>
        <td><%= experience.description %></td>
        <!-- <td><%= link_to 'Show', experience %></td> -->
        <td><%= link_to 'Edit', edit_experience_path(experience) %>
        <span class= "glyphicon glyphicon-edit" ></span>
        </td>
        <td><%= link_to 'Destroy', experience, method: :delete, data: { confirm: 'Are you sure?' } %>
        <span class= "glyphicon glyphicon-remove" ></span>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Work Experience', new_experience_path, class: "btn btn-default" %>


<!-- Modal -->
<div class="modal fade" id="expModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="expLabel"> Hello </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="expBody">
        World
      </div>
      
    </div>
  </div>
</div>

app/views/dashboard/honors.html.erb
<head>
      <%= javascript_include_tag :defaults %>
         <%= csrf_meta_tag %>
</head>


<table class="table table-hover table-bordered">
  <thead>
    <tr>
      <th>Honor date</th>
      <th>Honor name</th>
      <th>Honor description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody id="honorsList">
    <% @honors.each do |honor| %>
      <tr data-toggle="modal" data-target="#honModal">

        <td><%= honor.honor_date %></td>
        <td><%= honor.honor_name %></td>
        <td><%= honor.honor_description %></td>
        <!-- <td><%= link_to 'Show', honor %></td> -->
        <td><%= link_to 'Edit', edit_honor_path(honor) %>
        <span class= "glyphicon glyphicon-edit" ></span></td>
        <td><%= link_to 'Destroy', honor, method: :delete, data: { confirm: 'Are you sure?' } %>
        <span class= "glyphicon glyphicon-remove" ></span>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Honor or Award', new_honor_path, class: "btn btn-default" %>


<!-- Modal -->
<div class="modal fade" id="honModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="honLabel"> Hello </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="honBody">
        World
      </div>
      
    </div>
  </div>
</div>

app/views/dashboard/index.html.erb
<% if user_signed_in? %>
    <h1><%= current_user.first_name %> <%= current_user.last_name %></h1>
<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingOne">
      <h4 class="panel-title">
        <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
        	
					<h2> Experiences</h2>
					
        </a>
      </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
      <div class="panel-body">
      	
					
						<table class="table table-hover">
						  <thead>
						    <tr>
						
						      <th>Start date</th>
						      <th>End date</th>
						      <th>Name</th>
						      <th>Description</th>
						      <th colspan="3"></th>
						    </tr>
						  </thead>
						
						  <tbody id="experienceList">
						    <% @experiences.each do |experience| %>
						      <tr data-toggle="modal" data-target="#expModal">
						
						        <td><%= experience.start_date %></td>
						        <td><%= experience.end_date %></td>
						        <td><%= experience.name %></td>
						        <td><%= experience.description %></td>
						        <!-- <td><%= link_to 'Show', experience %></td> -->
						        <td><%= link_to 'Edit', edit_experience_path(experience) %>
						        <span class= "glyphicon glyphicon-edit" ></span>
						        </td>
						        <td><%= link_to 'Destroy', experience, method: :delete, data: { confirm: 'Are you sure?' } %>
						        <span class= "glyphicon glyphicon-remove" ></span>
						        </td>
						      </tr>
						    <% end %>
						  </tbody>
						</table>
						
						
						
						</div>
				    </div>
				  </div>
				  <div class="panel panel-default">
				    <div class="panel-heading" role="tab" id="headingTwo">
				      <h4 class="panel-title">
				        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
				        	
				          <h2> Skills </h2>
				          
				        </a>
				      </h4>
				    </div>
				    <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
				      <div class="panel-body">
						
						
						<table class="table table-hover">
						  <thead>
						    <tr>
						
						      <th>Skill name</th>
						      <th>Skill description</th>
						      <th colspan="3"></th>
						    </tr>
						  </thead>
						
						  <tbody id="skillsList">
						    <% @skills.each do |skill| %>
						     <tr data-toggle="modal" data-target="#skillModal">
						
						        <td><%= skill.skill_name %></td>
						        <td><%= skill.skill_description %></td>
						       <!-- <td><%= link_to 'Show', skill %></td> -->
						        <td><%= link_to 'Edit', edit_skill_path(skill) %>
						        <span class= "glyphicon glyphicon-edit" ></span></td>
						        <td><%= link_to 'Destroy', skill, method: :delete, data: { confirm: 'Are you sure?' } %>
						        <span class= "glyphicon glyphicon-remove" ></span>
						        </td>
						      </tr>
						    <% end %>
						  </tbody>
						</table>


						</div>
						    </div>
						  </div>
						  <div class="panel panel-default">
						    <div class="panel-heading" role="tab" id="headingThree">
						      <h4 class="panel-title">
						        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
						          
				    					<h2> Honors</h2>
				    					
						        </a>
						      </h4>
						    </div>
						    <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
						      <div class="panel-body">

					<!--	<%= link_to "Work Experience", { :controller => :dashboard, :action => :experience} %> -->
						
				    
						<table class="table table-hover">
						  <thead>
						    <tr>
						      <th>Honor date</th>
						      <th>Honor name</th>
						      <th>Honor description</th>
						      <th colspan="3"></th>
						    </tr>
						  </thead>
						
						  <tbody id="honorsList">
						    <% @honors.each do |honor| %>
						      <tr data-toggle="modal" data-target="#honModal">
						
						        <td><%= honor.honor_date %></td>
						        <td><%= honor.honor_name %></td>
						        <td><%= honor.honor_description %></td>
						        <!-- <td><%= link_to 'Show', honor %></td> -->
						        <td><%= link_to 'Edit', edit_honor_path(honor) %>
						        <span class= "glyphicon glyphicon-edit" ></span></td>
						        <td><%= link_to 'Destroy', honor, method: :delete, data: { confirm: 'Are you sure?' } %>
						        <span class= "glyphicon glyphicon-remove" ></span>
						        </td>
						      </tr>
						    <% end %>
						  </tbody>
						</table>
						
						</div>
					    </div>
					  </div>
					  <div class="panel panel-default">
					    <div class="panel-heading" role="tab" id="headingFour">
					      <h4 class="panel-title">
					        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
					          
					         	<h2> References</h2>
					         	
					        </a>
					      </h4>
					    </div>
					    <div id="collapseFour" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingFour">
					      <div class="panel-body">
							
						
							<table class="table table-hover">
							  <thead>
							    <tr>
							
							      <th>Reference name</th>
							      <th>Reference contact info</th>
							      <th colspan="3"></th>
							    </tr>
							  </thead>
							
							  <tbody id="referencesList">
							    <% @references.each do |reference| %>
							     <tr data-toggle="modal" data-target="#refModal">
							
							        <td><%= reference.reference_name %></td>
							        <td><%= reference.reference_contact_info %></td>
							        <!-- <td><%= link_to 'Show', reference %></td> -->
							        <td><%= link_to 'Edit', edit_reference_path(reference) %>
							        <span class= "glyphicon glyphicon-edit" ></span></td>
							        <td><%= link_to 'Destroy', reference, method: :delete, data: { confirm: 'Are you sure?' } %>
							        <span class= "glyphicon glyphicon-remove" ></span>
							        </td>
							      </tr>
							    <% end %>
							  </tbody>
							</table>
						 </div>
				    </div>
				  </div>
				</div>
						
					<!--	<%= link_to "Skills and Interests", { :controller => :dashboard, :action => :skills} %> -->
				
				    <br>

				<!--		<%= link_to "Honors and Awards", { :controller => :dashboard, :action => :honors} %> -->

				    <br>

				<!--		<%= link_to "References", { :controller => :dashboard, :action => :references } %> -->

	               <br>
	                   
<% end %> 



<!-- Modal -->
<div class="modal fade" id="expModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="expLabel"> Hello </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="expBody">
        World
      </div>
      
    </div>
  </div>
</div>


<!-- Modal -->
<div class="modal fade" id="skillModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="skillLabel"> Hello </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="skillBody">
        World
      </div>
      
    </div>
  </div>
</div>


<!-- Modal -->
<div class="modal fade" id="honModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="honLabel"> Hello </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="honBody">
        World
      </div>
      
    </div>
  </div>
</div>


<!-- Modal -->
<div class="modal fade" id="refModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="refLabel"> Hello </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="refBody">
        World
      </div>
      
    </div>
  </div>
</div>

app/views/dashboard/references.html.erb
<head>
      <%= javascript_include_tag :defaults %>
         <%= csrf_meta_tag %>
</head>


<table class="table table-hover table-bordered">
  <thead>
    <tr>

      <th>Reference name</th>
      <th>Reference contact info</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody id="referencesList">
    <% @references.each do |reference| %>
      <tr data-toggle="modal" data-target="#refModal">

        <td><%= reference.reference_name %></td>
        <td><%= reference.reference_contact_info %></td>
        <!-- <td><%= link_to 'Show', reference %></td> -->
        <td><%= link_to 'Edit', edit_reference_path(reference) %>
        <span class= "glyphicon glyphicon-edit" ></span></td>
        <td><%= link_to 'Destroy', reference, method: :delete, data: { confirm: 'Are you sure?' } %>
        <span class= "glyphicon glyphicon-remove" ></span>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reference', new_reference_path, class: "btn btn-default" %>

<!-- Modal -->
<div class="modal fade" id="refModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="refLabel"> Hello </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="refBody">
        World
      </div>
      
    </div>
  </div>
</div>

app/views/dashboard/skills.html.erb
<head>
      <%= javascript_include_tag :defaults %>
         <%= csrf_meta_tag %>
</head>


<table class="table table-hover table-bordered">
  <thead>
    <tr>

      <th>Skill name</th>
      <th>Skill description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody id="skillsList">
    <% @skills.each do |skill| %>
      <tr data-toggle="modal" data-target="#skillModal">

        <td><%= skill.skill_name %></td>
        <td><%= skill.skill_description %></td>
       <!-- <td><%= link_to 'Show', skill %></td> -->
        <td><%= link_to 'Edit', edit_skill_path(skill) %>
        <span class= "glyphicon glyphicon-edit" ></span></td>
        <td><%= link_to 'Destroy', skill, method: :delete, data: { confirm: 'Are you sure?' } %>
        <span class= "glyphicon glyphicon-remove" ></span>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Skill or Interest', new_skill_path, class: "btn btn-default" %>

<!-- Modal -->
<div class="modal fade" id="skillModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="skillLabel"> Hello </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="skillBody">
        World
      </div>
      
    </div>
  </div>
</div>